### ISSUE TITLE
Infra Checklist

### ISSUE THREAD

**Issue by jrhite** [omisego/omg-load-testing#19]
- [ ] Helm Charts: update for fees

    **Details**
    For now, set `ignore_fees: false` for load testing environments.
    Slack conversation: https://omisego.slack.com/archives/C9KNA675J/p1580704936302800

- [ ] Helm Charts: update charts setting app environment to be logical env name

    **Details**
    Set `APP_ENV: loadtesting` for all load testing clusters.
    Reference issue: https://github.com/omisego/devops/issues/317

- [ ] Helm Charts: bypass Cloudfare CDN

    **Details**
    Awaiting merge of https://github.com/omisego/helm-development/pull/53

- [ ] Updates to truffle deployments

    **Details**
    Needs investigation, not sure how/if this will affect us yet or if its our responsibility
    Slack conversation: https://omisego.slack.com/archives/CMX790Q5V/p1580892415052500I 

    Migration step 2 has been altered so that the maintainer account sets a semver version on the plasma framework contract: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/migrations/2_deploy_plasma_framework.js#L24-L25

    This value is later read by watcher, watcher info and child chain.

**Comment by kevsul** [comment]
Can we set `ignore_fees: true` for now?

**Comment by jrhite** [comment]
@kevsul my bad, yes, sorry...hehe. let me fix that typo.
